package policy

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/alisaitteke/sideguard/internal/paths"
)

// DevWorkspacePolicy writes repo-scoped allow rules for common dev tooling (make, go, scripts/).
// Used by `sideguard install --dev` and `sideguard policy init-dev` so agents developing
// SideGuard in Cursor are not deadlocked by their own hooks. Production users are unaffected.
func DevWorkspacePolicy(repoRoot string) (string, error) {
	abs, err := filepath.Abs(repoRoot)
	if err != nil {
		return "", fmt.Errorf("resolve repo root: %w", err)
	}
	abs = filepath.Clean(abs)
	pathPat := fmt.Sprintf("^%s(/.*)?$", regexp.QuoteMeta(abs))

	var b strings.Builder
	b.WriteString("# SideGuard workspace dev policy — repo-scoped allow rules for local development.\n")
	b.WriteString("# Generated by sideguard install --dev or sideguard policy init-dev.\n")
	b.WriteString("# Edit or delete this file to tighten scope. Does not affect other projects.\n")
	b.WriteString("rules:\n")

	rules := []struct {
		command string
		reason  string
	}{
		{`^make\b`, "repo dev tooling (workspace policy)"},
		{`^go (test|build|vet|run|generate|fmt|mod)\b`, "repo dev tooling (workspace policy)"},
		{`^(bash|sh) scripts/`, "repo dev scripts (workspace policy)"},
	}
	for _, r := range rules {
		fmt.Fprintf(&b, "  - match:\n      path: %q\n      command: %q\n    action: allow\n    reason: %q\n",
			pathPat, r.command, r.reason)
	}
	return b.String(), nil
}

// EnsureDevWorkspacePolicy writes .sideguard/policy.yaml under repoRoot when missing.
// Returns the file path and whether a new file was created.
func EnsureDevWorkspacePolicy(repoRoot string) (path string, created bool, err error) {
	abs, err := filepath.Abs(repoRoot)
	if err != nil {
		return "", false, fmt.Errorf("resolve repo root: %w", err)
	}
	abs = filepath.Clean(abs)

	dir := filepath.Join(abs, paths.DirName)
	path = filepath.Join(dir, paths.PolicyFile)
	if _, err := os.Stat(path); err == nil {
		return path, false, nil
	} else if !os.IsNotExist(err) {
		return "", false, fmt.Errorf("stat workspace policy: %w", err)
	}

	content, err := DevWorkspacePolicy(abs)
	if err != nil {
		return "", false, err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", false, fmt.Errorf("create workspace policy dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return "", false, fmt.Errorf("write workspace policy: %w", err)
	}
	return path, true, nil
}
